
export const REPORT_PROGRAM_SERVICES = [
  'Promosi Kesehatan',
  'Kesehatan Ibu',
  'Kesehatan Anak',
  'UKS',
  'Kesehatan Remaja',
  'Kesehatan Reproduksi',
  'Kesehatan Lansia',
  'Gizi',
  'Kesehatan Lingkungan',
  'TB',
  'HIV',
  'Kusta dan frambusia',
  'Ispa',
  'Hepatitis',
  'Diare',
  'Imunisasi',
  'Surveilans',
  'Penyakit tidak menular',
  'Kesehatan Indera',
  'Kesehatan Jiwa',
  'Kanker',
  'P2BB (Penyakit bersumber Binatang)',
  'Perkesmas',
  'PIS PK',
  'Kesehatan kerja dan olahraga',
  'UKGS UKGMD',
  'Yankestrad',
  'Haji',
  'Ngider sehat',
] as const;
